"""add allocations

Revision ID: e04e348f9708
Revises: 0a9a8c9ebc4e
Create Date: 2026-06-28 13:07:11.809918

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e04e348f9708'
down_revision: Union[str, None] = '0a9a8c9ebc4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('allocations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('monthly_plan_id', sa.Uuid(), nullable=False),
    sa.Column('category_id', sa.Uuid(), nullable=False),
    sa.Column('allocated_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['monthly_plan_id'], ['monthly_plans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('monthly_plan_id', 'category_id', name='uq_plan_category')
    )
    op.create_index(op.f('ix_allocations_category_id'), 'allocations', ['category_id'], unique=False)
    op.create_index(op.f('ix_allocations_monthly_plan_id'), 'allocations', ['monthly_plan_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_allocations_monthly_plan_id'), table_name='allocations')
    op.drop_index(op.f('ix_allocations_category_id'), table_name='allocations')
    op.drop_table('allocations')
    # ### end Alembic commands ###
